title: Underfitting and Overfitting in Software Development
description: An analysis of underfitting and overfitting concepts in software development and organizational models
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  toc_levels: 1..3
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - chapters/*.md
  - visualizations.md

# Navigation links
header_pages:
  - README.md
  - visualizations.md
  
# Site author
author:
  name: Klaus Eduard
  
# Social links
github_username: klauseduard 